In [1]:
import msoffcrypto
import io
import pandas as pd
from pyxlsb import open_workbook
import os
import numpy as np
import calendar

C:\Users\Neil\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
# Define the folder path
folder_path = "C:/Users/Neil/OneDrive/Documents/Capstone Files/worst_del_home"

# List all Excel files in the folder
file_list = [f for f in os.listdir(folder_path) if f.endswith('.xlsx')]

# Initialize an empty list to store DataFrames
df_list = []

# Read each file and store in df_list
for file in file_list:
    file_path = os.path.join(folder_path, file)
    df = pd.read_excel(file_path)  # Read the Excel file
    df_list.append(df)
    print(f"Loaded: {file}")  # Print each loaded file

# Check if any files were found
if not df_list:
    print("No Excel files found in the folder.")
else:
    print(f"Successfully loaded {len(df_list)} files.")

Loaded: merged_worst_delinquency_H1.xlsx
Loaded: merged_worst_delinquency_H2.xlsx
Loaded: merged_worst_delinquency_H3.xlsx
Loaded: merged_worst_delinquency_H4.xlsx
Successfully loaded 4 files.

In [3]:
merged_df = df_list[0]
    
    # Merge all DataFrames in the list using an outer join
for df in df_list[1:]:
        merged_df = pd.merge(merged_df, df, on="ILS_ACCT_NUM", how="outer")

    # Print the merged DataFrame
print(merged_df)

          ILS_ACCT_NUM  WORST_DELINQUENCY JAN 2015  \
0      232001000330243                         1.0
1      232001002826911                         0.0
2      232001009874040                         NaN
3      232002000129304                         0.0
4      232002000651195                         1.0
...                ...                         ...
55122  266996000244801                         0.0
55123  266996000935412                         0.0
55124  266998000881994                         1.0
55125  266998000900186                         0.0
55126  266998000930773                         0.0

       WORST_DELINQUENCY FEB 2015  WORST_DELINQUENCY MAR 2015  \
0                             1.0                         1.0
1                             0.0                         0.0
2                             NaN                         NaN
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY APR 2015  WORST_DELINQUENCY MAY 2015  \
0                             1.0                         1.0
1                             0.0                         0.0
2                             NaN                         NaN
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY JUN 2015  WORST_DELINQUENCY JUL 2015  \
0                             1.0                         1.0
1                             0.0                         0.0
2                             NaN                         NaN
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY AUG 2015  WORST_DELINQUENCY SEP 2015  ...  \
0                             1.0                         1.0  ...
1                             0.0                         0.0  ...
2                             NaN                         NaN  ...
3                             0.0                         0.0  ...
4                             1.0                         1.0  ...
...                           ...                         ...  ...
55122                         0.0                         0.0  ...
55123                         0.0                         0.0  ...
55124                         1.0                         1.0  ...
55125                         0.0                         0.0  ...
55126                         0.0                         0.0  ...

       WORST_DELINQUENCY MAR 2024  WORST_DELINQUENCY APR 2024  \
0                             1.0                         1.0
1                             3.0                         3.0
2                             0.0                         0.0
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY MAY 2024  WORST_DELINQUENCY JUN 2024  \
0                             1.0                         1.0
1                             3.0                         3.0
2                             0.0                         0.0
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY JUL 2024  WORST_DELINQUENCY AUG 2024  \
0                             1.0                         1.0
1                             3.0                         3.0
2                             0.0                         0.0
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY SEP 2024  WORST_DELINQUENCY OCT 2024  \
0                             1.0                         1.0
1                             3.0                         3.0
2                             0.0                         0.0
3                             0.0                         0.0
4                             1.0                         1.0
...                           ...                         ...
55122                         0.0                         0.0
55123                         0.0                         0.0
55124                         1.0                         1.0
55125                         0.0                         0.0
55126                         0.0                         0.0

       WORST_DELINQUENCY NOV 2024  WORST_DELINQUENCY DEC 2024
0                             1.0                           1
1                             3.0                           3
2                             0.0                           0
3                             0.0                           0
4                             1.0                           1
...                           ...                         ...
55122                         0.0                           0
55123                         0.0                           0
55124                         1.0                           1
55125                         0.0                           0
55126                         0.0                           0

[55127 rows x 121 columns]

In [4]:
file_path = 'C:/Users/Neil/OneDrive/Documents/Capstone Files/Extracted Datasets/HOME/2024/12 ILS HOME DEC 2024 CONSO.xlsb'
password = "CRQAD_amf_2025!"

# Decrypt the file
decrypted = io.BytesIO()
with open(file_path, "rb") as f:
    office_file = msoffcrypto.OfficeFile(f)
    office_file.load_key(password=password)
    office_file.decrypt(decrypted)

# Read the decrypted `.xlsb` file
decrypted.seek(0)  # Reset pointer before reading

data = []
with open_workbook(decrypted) as wb:
    sheet_name = list(wb.sheets)[0]  # Get the first sheet name
    print(f"Opening Sheet: {sheet_name}")

    # Read sheet data
    with wb.get_sheet(sheet_name) as sheet:
        for row in sheet.rows():
            data.append([item.v for item in row])

# Convert to DataFrame
df = pd.DataFrame(data)
df.columns = df.iloc[0]  # Assign first row as column names
df = df[1:].reset_index(drop=True)  # Remove the first row from data

# Display first few rows
print(df.head())

Opening Sheet: Sheet1
0 APPRAISAL_DATE APPRAISAL_RATE APPRAISAL_VALUE   BOOK_DATE BOOK_VALUE  \
0           None          100.0             0.0  03/19/2003        0.0
1           None           70.0       3192000.0  06/26/2008        0.0
2           None           60.0        216000.0  10/25/2002        0.0
3           None           70.0       1000000.0  05/23/2001        0.0
4     09/19/2007          100.0        107100.0  12/10/2007        0.0

0 CAR_DESCRIPTION CAR_MANUFACTURER CAR_MODEL  CLOSE_DATE COLLATERAL_CONDITION  \
0            None             None      None  03/18/2008                  0.0
1            None             None      None  06/13/2012                  0.0
2            None             None      None  10/25/2007                  0.0
3            None             None      None  05/23/2011                  0.0
4            None             None      None  08/09/2008                  0.0

0  ...    RM_NO CLNT_TYPE Total Interest Payment Total Principal Payment  \
0  ...  8972790         P               85110.58               434109.83
1  ...  2005978         P              103434.01               495538.53
2  ...    94507         P               21866.43                99681.29
3  ...   266267         P              295423.71               774905.53
4  ...  8807804         P               26941.82                47446.76

0 ADJ_DELQ_AGE_ACTUAL    PD EDITED_PURPOSE COLLATERAL_TYPE_DESCRIPTION  \
0                None  None         Others              REGISTERED REM
1                None  None         Others              REGISTERED REM
2                None  None         Others              REGISTERED REM
3                None  None         Others              REGISTERED REM
4                None  None         Others              REGISTERED REM

0 EDITED_COLLATERAL_TYPE      FOR REM
0                    REM  Unspecified
1                    REM  Unspecified
2                    REM  Unspecified
3                    REM  Unspecified
4                    REM  Unspecified

[5 rows x 81 columns]

In [5]:
df

,APPRAISAL_DATE,APPRAISAL_RATE,APPRAISAL_VALUE,BOOK_DATE,BOOK_VALUE,CAR_DESCRIPTION,CAR_MANUFACTURER,CAR_MODEL,CLOSE_DATE,COLLATERAL_CONDITION,...,RM_NO,CLNT_TYPE,Total Interest Payment,Total Principal Payment,ADJ_DELQ_AGE_ACTUAL,PD,EDITED_PURPOSE,COLLATERAL_TYPE_DESCRIPTION,EDITED_COLLATERAL_TYPE,FOR REM
0,None,100.0,0.0,03/19/2003,0.0,None,None,None,03/18/2008,0.0,...,8972790,P,85110.58,434109.83,None,None,Others,REGISTERED REM,REM,Unspecified
1,None,70.0,3192000.0,06/26/2008,0.0,None,None,None,06/13/2012,0.0,...,2005978,P,103434.01,495538.53,None,None,Others,REGISTERED REM,REM,Unspecified
2,None,60.0,216000.0,10/25/2002,0.0,None,None,None,10/25/2007,0.0,...,94507,P,21866.43,99681.29,None,None,Others,REGISTERED REM,REM,Unspecified
3,None,70.0,1000000.0,05/23/2001,0.0,None,None,None,05/23/2011,0.0,...,266267,P,295423.71,774905.53,None,None,Others,REGISTERED REM,REM,Unspecified
4,09/19/2007,100.0,107100.0,12/10/2007,0.0,None,None,None,08/09/2008,0.0,...,8807804,P,26941.82,47446.76,None,None,Others,REGISTERED REM,REM,Unspecified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55122,11/05/2024,100.0,7049167.55,12/05/2024,2184700.0,None,None,None,None,None,...,4912910341,P,0.0,0.0,0.0,0.0,Construction,REGISTERED REM,REM,House & Lot
55123,06/04/2024,100.0,50565943.0,12/16/2024,2000000.0,None,None,None,None,None,...,4912038039,P,0.0,0.0,0.0,0.0,PI-AP,REGISTERED REM,REM,Unspecified
55124,06/11/2024,100.0,8559500.0,12/13/2024,8525000.0,None,None,None,None,None,...,21093587,P,0.0,0.0,0.0,0.0,Acquisition,CLEAN,Others,Condominium
55125,11/25/2024,100.0,2334294.0,12/27/2024,3104395.9,None,None,None,None,None,...,9674814,P,0.0,0.0,0.0,0.0,Acquisition,CLEAN,Others,Condominium
55126,10/23/2024,100.0,3244000.0,12/06/2024,2588800.0,None,None,None,None,None,...,21124595,P,0.0,0.0,0.0,0.0,Acquisition,CLEAN,Others,House & Lot

In [6]:
key_column = "ILS_ACCT_NUM"

# Convert key column to string in both DataFrames
merged_df[key_column] = merged_df[key_column].astype(str)
df[key_column] = df[key_column].astype(str)

# Extract required columns
book_date_df = df[[key_column, "ORIG_BOOK_DATE", "MATURITY", "PRODUCT_TYPE"]]

# Merge, ensuring new columns come first
merged_df = pd.merge(book_date_df, merged_df, on=key_column, how="left")

print(merged_df.dtypes)  # Check data types to confirm
print(merged_df.head())  # Verify output

ILS_ACCT_NUM                   object
ORIG_BOOK_DATE                 object
MATURITY                       object
PRODUCT_TYPE                   object
WORST_DELINQUENCY JAN 2015    float64
                               ...
WORST_DELINQUENCY AUG 2024    float64
WORST_DELINQUENCY SEP 2024    float64
WORST_DELINQUENCY OCT 2024    float64
WORST_DELINQUENCY NOV 2024    float64
WORST_DELINQUENCY DEC 2024      int64
Length: 124, dtype: object
      ILS_ACCT_NUM ORIG_BOOK_DATE    MATURITY PRODUCT_TYPE  \
0  266517000260174     03/19/2003  03/18/2008        177.0
1  266070000201309     06/13/2002  06/13/2012        177.0
2  261857000273764     10/25/2002  10/25/2007        174.0
3  261218000267639     05/23/2001  05/23/2011        174.0
4  261220000155926     12/10/2007  12/10/2012        174.0

   WORST_DELINQUENCY JAN 2015  WORST_DELINQUENCY FEB 2015  \
0                         1.0                         1.0
1                         0.0                         0.0
2                         1.0                         1.0
3                         2.0                         2.0
4                         0.0                         0.0

   WORST_DELINQUENCY MAR 2015  WORST_DELINQUENCY APR 2015  \
0                         1.0                         1.0
1                         0.0                         0.0
2                         1.0                         1.0
3                         2.0                         2.0
4                         0.0                         0.0

   WORST_DELINQUENCY MAY 2015  WORST_DELINQUENCY JUN 2015  ...  \
0                         1.0                         1.0  ...
1                         0.0                         0.0  ...
2                         1.0                         1.0  ...
3                         2.0                         2.0  ...
4                         0.0                         0.0  ...

   WORST_DELINQUENCY MAR 2024  WORST_DELINQUENCY APR 2024  \
0                         1.0                         1.0
1                         0.0                         0.0
2                         1.0                         1.0
3                         2.0                         2.0
4                         0.0                         0.0

   WORST_DELINQUENCY MAY 2024  WORST_DELINQUENCY JUN 2024  \
0                         1.0                         1.0
1                         0.0                         0.0
2                         1.0                         1.0
3                         2.0                         2.0
4                         0.0                         0.0

   WORST_DELINQUENCY JUL 2024  WORST_DELINQUENCY AUG 2024  \
0                         1.0                         1.0
1                         0.0                         0.0
2                         1.0                         1.0
3                         2.0                         2.0
4                         0.0                         0.0

   WORST_DELINQUENCY SEP 2024  WORST_DELINQUENCY OCT 2024  \
0                         1.0                         1.0
1                         0.0                         0.0
2                         1.0                         1.0
3                         2.0                         2.0
4                         0.0                         0.0

   WORST_DELINQUENCY NOV 2024  WORST_DELINQUENCY DEC 2024
0                         1.0                           1
1                         0.0                           0
2                         1.0                           1
3                         2.0                           2
4                         0.0                           0

[5 rows x 124 columns]

In [8]:
merged_df.to_csv("WORST_DELINQUENCY_HOME.csv", index=False)